### ISSUE TITLE
joto_tool and jotoba_resources appear to be a private repos, but are linked in the README

### ISSUE THREAD

**Issue by marksg07** [WeDontPanic/Jotoba#10]
I can't access jototool at this url: https://github.com/WeDontPanic/joto_tool or jotoba_resources at this url: https://github.com/WeDontPanic/jotoba_resources

**Comment by JojiiOfficial** [comment]
That's correct. We haven't stabilized that part yet. See #3

**Comment by marksg07** [comment]
Thank you! Is your discord public information? :P

**Comment by JojiiOfficial** [comment]
If you join the Jotoba discord, yes

**Comment by JojiiOfficial** [comment]
Currently not planned to be made public.
