### ISSUE TITLE
Add pitch accent data to the API

### ISSUE THREAD

**Issue by marksg7** [WeDontPanic/Jotoba#12]
**Is your feature request related to a problem? Please describe.**
I would expect that since it's part of the data of a word entry, it would be returned in the word API.

**Describe the solution you'd like**
Add a field to the word schema like: 
`pitches: [d1, d2, ...]` where each entry is the index at which the pitch drops (or whatever format you see fit to report pitch drops in)

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by JojiiOfficial** [comment]
Feature request will be tracked on the trello board. Closing this since it'll be added to the roadmap.
