### ISSUE TITLE
Display odaka pitch accent more explicitly

### ISSUE THREAD

**Issue by jeifour** [WeDontPanic/Jotoba#15]
**Is your feature request related to a problem? Please describe.**
Currently for words with odaka pitch, the down-step isn't displayed. This makes it impossible to distinguish from heiban pitch when the word has only 2 morae.

**Describe the solution you'd like**
The down-step should always be shown explicitly, even for words with odaka pitch.

**Describe alternatives you've considered**
There are also other ways to display pitch accent of course. Whatever way is chosen, it should always be possible to discern if the mora that is following the word in question has a high or low pitch.

**Additional context**
A search for "kaki" would for example show you the following words (柿 [0] and 垣 [2]). Even though both have different accents, the result looks the same.

![スクリーンショット 2021-11-21 19 45 43](https://user-images.githubusercontent.com/3247063/142775123-c0179a51-ada7-4aa4-ba0c-8275b01ce76a.png)

**Comment by JojiiOfficial** [comment]
Already fixed in #11. Coming to Jotoba.de in the next patch.
