### ISSUE TITLE
Double results

### ISSUE THREAD

**Issue by jeifour** [WeDontPanic/Jotoba#16]
**Describe the bug**
When I search for "kaki" (using romaji), the entry for 柿 shows up twice. It also behaves weirdly.

**To Reproduce**
1. Go to [the results page for "kaki"](https://jotoba.de/search/kaki?t=0) or search for it manually
2. Scroll down until you see both entries for 柿
3. Try to open up the menu on the right side of the entries. Only the menu button of the upper entry works. It will however open up and close both menus at the same time, indicating that something unintended happened.

**Expected behavior**
The 柿 entry should only show up once in the results page.

**Screenshots**
![スクリーンショット 2021-11-21 19 46 18](https://user-images.githubusercontent.com/3247063/142775322-fbc82043-52d0-4337-b653-afd8f5a29b77.png)
Screencast (~15 secs, available until Nov 25): https://filesend.standardnotes.com/send/SMsRYRGdhMtdEPEdll7M#MmQ2ZDEwOTcxYzlmZTEyMGY4N2Jm

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Safari 15.1

**Additional context**
I have no clue why this might be happening, but it seems reproducible. I couldn't find another search query until now that shows the same behavior.

**Comment by JojiiOfficial** [comment]
Thanks for reporting. I'll look into it
