### ISSUE TITLE
Inconsistent voice indicator

### ISSUE THREAD

**Issue by MoshiKoi** [WeDontPanic/Jotoba#17]
**Describe the bug**

On the home page of Jotoba, the microphone button is always grey, whether recording is on or not:
![image](https://user-images.githubusercontent.com/54333972/142808165-2adfb50f-bb8b-44d5-ab42-69bf0527a31d.png)

However, on the search results page, it shows as green whether recording is on or not:
![image](https://user-images.githubusercontent.com/54333972/142808151-265c9364-347a-47cb-9265-3f96afee3ee1.png)

**Expected behavior**

Recording light would turn green when recording and off when not recording

**Desktop (please complete the following information):**

Windows 11 Edge

**Comment by Yukaru-san** [comment]
Not a bug but a design choice. On search result pages the icon is green because the search-icon is green aswell. It is not meant to turn green when recording - however, I do like the idea.

**Comment by Yukaru-san** [comment]
Implemented on dev. It will be available in the next patch.
