### ISSUE TITLE
Double clicking kanji-less words gives "meaning copied to clipboard"

### ISSUE THREAD

**Issue by MoshiKoi** [WeDontPanic/Jotoba#18]
**Describe the bug**
Basically the title. Double clicking on word entries that don't have kanji gives a "meaning copied to clipboard" popup; for instance, if you double click [アルバイト](https://jotoba.de/search/%E3%82%A2%E3%83%AB%E3%83%90%E3%82%A4%E3%83%88?t=0), it says that, however, アルバイト is copied.

I'm not sure whether the message is incorrect (and it should say something like "word copied to clipboard", and this is a translation/interface correction) or if the action is incorrect (and it should copy the dictionary entry)

**To Reproduce**
1. Go to [アルバイト](https://jotoba.de/search/%E3%82%A2%E3%83%AB%E3%83%90%E3%82%A4%E3%83%88?t=0)
2. Double click on アルバイト
3. "meaning copied to clipboard" pops up even though it is actually the word that is copied.

**Expected behavior**
Either it copies the meaning like the popup says, or the popup message tells me that the word is copied.

**Desktop (please complete the following information):**
Windows 11 Edge

**Comment by Yukaru-san** [comment]
Not a bug, it does what it's intended to do. I'll change the message's text.
