### ISSUE TITLE
Jisho-esque wildcard search

### ISSUE THREAD

**Issue by marksg7** [WeDontPanic/Jotoba#20]
**Is your feature request related to a problem? Please describe.**
Since this project is aimed at being an open-source replacement for internet dictionaries, such as Jisho, I think this feature would be nice to have since it's pretty helpful.

**Describe the solution you'd like**
In search queries, have * match any characters and ? match any single character. We could possibly do more if there's demand but this is the set of functionality Jisho implements so I figure it's a good jumping-off point.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by JojiiOfficial** [comment]
Has already been [added](https://trello.com/c/ZlC0Bhcz/337-implement-advanced-search-using-regex-style-components) to the roadmap. Closing since feature requests are tracked there
