### ISSUE TITLE
Dark Mode Kanji Stroke Diagrams

### ISSUE THREAD

**Issue by MoshiKoi** [WeDontPanic/Jotoba#22]
**Is your feature request related to a problem? Please describe.**
The next stroke of kanji is barely visible when using dark mode:

![image](https://user-images.githubusercontent.com/54333972/143152085-4971281f-8fde-43d4-9a50-32511084eb92.png)

**Describe the solution you'd like**
Please make the new stroke white instead of black when using dark mode.

**Comment by Yukaru-san** [comment]
This will be implemented with the next patch. Further progress is tracked on [Trello](https://trello.com/c/VQz29XGA/381-22-dark-mode-kanji-stroke-diagrams).
