### ISSUE TITLE
Vietnamese reading of kanji 

### ISSUE THREAD

**Issue by WaterZoopPlein** [WeDontPanic/Jotoba#27]
**Is your feature request related to a problem? Please describe.**
Vietnamese reading of kanji in the kanji page.

**Describe the solution you'd like**
The most recent EDRDG's KANJIDIC2 has a field that indicate Vietnamese reading(s) of kanji. I am not sure which version of KANJIDIC2 Jotoba is using but it would be nice if it manages to get the readings from the later KANJIDIC2.

**Describe alternatives you've considered**
n/a

**Additional context**
It can be very useful for Vietnamese speakers. They can use the readings to get the feel of the kanji meanings quickly without having to consult other dictionaries for every kanji looked up. It can also be a good mnemonic device too.

**Preview feature screenshot**
![image](https://user-images.githubusercontent.com/28999049/152265279-1ff730a1-6f00-4b90-be1d-b469f69e6516.png)

**Comment by JojiiOfficial** [comment]
https://trello.com/c/Gofk0TDX/450-vietnamese-readings-in-kanji

Planned to be added after next release

**Comment by JojiiOfficial** [comment]
Closed in 03caade
