### ISSUE TITLE
Audio playback in Safari (still) broken

### ISSUE THREAD

**Issue by Dorako** [WeDontPanic/Jotoba#28]
I realize this was marked as fixed in 1.2, but when I click 'Play audio' nothing happens. The linked audio file is still .ogg (which doesn't play back on certain browsers) and I don't see any javascript alleviate this issue.

**Comment by JojiiOfficial** [comment]
It has been fixed (more or less). We implemented a fallback to mp3 when those files exist. This is entirely done backend-wise. The reason its not working is that I forgot to place the mp3 audios on the server (my bad). So its always falling back to ogg

**Comment by Dorako** [comment]
Haha that's funny, works great now 😆
