### ISSUE TITLE
Missing Jotoba-resources to properly run the server

### ISSUE THREAD

**Issue by clnhs** [WeDontPanic/Jotoba#3]
Hi to both @JojiiOfficial and @Yukaru-san,

First, thank you for you work on this project. I'm glad to see an alternative to Jisho.org popping up, especially an open-source one. And with a workable open API at that!

 I'm currently working my way back into web dev and have been focusing on getting up to snuff with JS and React, and your project has me wanting to fork it to build my own UI for practice, possibly contribute on the frontend side of things.

So, I successfully got the server to build on macOS (had to go through [these steps](https://github.com/ccouzens/tesseract-sys/issues/6#issuecomment-850592277) for `tesseract-sys` to build) but am running into missing resources on run. 

The self-hosting wiki page points out to a Jotoba-resources repo which sadly ends up on a 404. Are you planning for the repo to be accessible sometime soon or is it delayed?

Thanks!

**Comment by JojiiOfficial** [comment]
Until now, only the server itself has been stabilized and documented. The tool to generate and the repository containing the compiled data aren't public yet. It'll take some time until we've stabilized this tool as well. I can give you the required resources personally if you want. For that dm me on discord and I'll share a link of the files. 

Thanks for sharing the tesseract issue, I'll reference that in the wiki. You can also compile Jotoba without the `img_scan` feature so you don't need tesseract to be installed.

**Comment by clnhs** [comment]
> Thanks for sharing the tesseract issue, I'll reference that in the wiki. 

No problem. Might also add that you can install mecab-unidic through brew as well.

> As for now, only the server itself has been stabilized and documented. The tool to generate and the repository containing the compiled data aren't public yet. It'll take some time until we've stabilized this tool as well.

Makes sense.

>  I can give you the required resources personally if you want. For that dm me on discord and I'll share a link of the files.

I'll take you up on your offer, thanks!
