### ISSUE TITLE
Refocus the search bar after hitting enter and searching, without having to press forward slash

### ISSUE THREAD

**Issue by sahlaysta** [WeDontPanic/Jotoba#37]
Feature request: Refocus the search bar after hitting enter and searching, without having to press forward slash

**Comment by JojiiOfficial** [comment]
This feature already exists. Although it is currently buggy and doesn't work (which I just found out). Is already been fixed and will available on jotoba.com within the next few hours.

You'll find it here:
![image](https://user-images.githubusercontent.com/15957865/176265033-6a7d7bc7-9246-4911-9075-063887789291.png)

**Comment by Yukaru-san** [comment]
I already implemented this feature and it seems to have been broken by a past change in how I handled the settings. 
You can activate it via: [Settings] -> SEARCH -> Focus search bar on load

I've fixed it just now and it will be live with the next update.

**Comment by JojiiOfficial** [comment]
Timing 100
