### ISSUE TITLE
Please implement OpenSearch

### ISSUE THREAD

**Issue by KarsMulder** [WeDontPanic/Jotoba#4]
The [OpenSearch](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) standard makes it possible for a website to inform the user's browser that it has a search engine, so the user can add that search engine to the browser, making it possible for them to type a word in their browsers' search bar and click on "Search with Jotoba" to quickly look up a word without having to navigate to Jotoba's home page first. I personally find this to make a big difference in the convenience of using a dictionary.

**Comment by Yukaru-san** [comment]
Thanks for the suggestion.
It will be implemented in our next update!

**Comment by JojiiOfficial** [comment]
Has been implemented. Coming next patch
