### ISSUE TITLE
For some words, sentences returned do not contain the word at all

### ISSUE THREAD

**Issue by aoussou** [WeDontPanic/Jotoba#42]
When looking for sentences containing a certain word, sentence that do not contain the word or expression are also returned. Example:

Example:

Look for sentences containing **ぽかんと** :

https://jotoba.de/search/%E3%81%BD%E3%81%8B%E3%82%93%E3%81%A8?t=2&p=1&l=en-US

Most sentences do not contain "ぽかんと" .

**Comment by JojiiOfficial** [comment]
Well this is not a word, at least not in the dataset Jotoba uses. It gets split into 'ぽかん' and 'と' so Jotoba searches for both. But sentences with both terms should have indeed more relevance.
