### ISSUE TITLE
API search page cannot be reached

### ISSUE THREAD

**Issue by DevNadine** [WeDontPanic/Jotoba#43]
The page "https://jotoba.de/api/search/words" can no longer be reached. I made myself a little tool to look up words by clicking them to avoid having to copy them over and I now get a message "The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed."

**Comment by JojiiOfficial** [comment]
Fixed

**Comment by DevNadine** [comment]
Thx
