### ISSUE TITLE
Kanji animations/ stroke orders no longer showing

### ISSUE THREAD

**Issue by yuba64** [WeDontPanic/Jotoba#44]
**Describe the bug**
On any Kanji being opened, there is no longer a way to see the animation/ stroke order image.

**To Reproduce**
Open any Kanji on the website and they will not be visible

**Expected behavior**
Kanji drawing animations and stroke order chart to be visible on Kanji page.

**Screenshots**
![image](https://user-images.githubusercontent.com/100544250/212145608-bfddea10-839f-40c6-bfd6-78fd096df0d6.png)

**Desktop (please complete the following information):**
 - OS: Windows (also the same on iOS)
 - Browser: Edge
**Smartphone (please complete the following information):**
 - Device: iPhone 7 plus
 - OS: Latest iOS
 - Browser: Edge and Safari

**Additional context**
Assuming this is intentional for now, although it would be great to have these features back at some point.
(just to note I am not a coder, just reporting this as I love the site)

Thanks!

**Comment by JojiiOfficial** [comment]
Hey, thanks for reporting this Issue!
It was actually not intended but a misconfiguration hard hardcoded paths. I wrote a fix which will be deployed in a few minutes
