### ISSUE TITLE
CTRL not working in Searchbar on Mac

### ISSUE THREAD

**Issue by GKJCJG** [WeDontPanic/Jotoba#47]
Before you file a bug report, check the [trello board](https://trello.com/b/nmG0xgaW/jotoba-roadmap) if this has already added on the road map.

**Describe the bug**
On MacOS, in Safari and Chrome at least, attempting to paste a search term into the search bar results in the character `v` appearing. 

**To Reproduce**
0. On MacOS
1. Copy some text to the clipboard (`Command + C`)
2. Try to paste that text in Jotoba's search form (`Command + V`)
3. The character `v` will be entered in the search form rather than your content.
> The same appears to be true of other common shortcuts: `Command + Z` to undo will write `z`; selecting text and attempting to copy using `Command + C` will instead replace the text with `c`; `Command + A` to select all will insert `a`, etc.

**Expected behavior**

The default action associated with the shortcut should be executed: paste for `Command + V`, copy for `Command + C`, undo for `Command + Z` etc.

**Screenshots**

![image](https://github.com/WeDontPanic/Jotoba/assets/43424668/2a3e257c-3806-4ee4-b5a9-0a0df1dd1f82)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome, Safari

**Comment by JojiiOfficial** [comment]
The issue _should_ be fixed. We don't own a Mac, so maybe someone using Mac could give feedback whether it works or not?

**Comment by GKJCJG** [comment]
It is fixed. Thank you!
