### ISSUE TITLE
な particle is a verb

### ISSUE THREAD

**Issue by luckasRanarison** [WeDontPanic/Jotoba#48]
な particle after na-adjectives is shown as a verb.
![Screenshot_20230910-081735~2](https://github.com/WeDontPanic/Jotoba/assets/101930730/18f41cb0-6cb4-4d69-8a7b-105a734224be)
By the way, I took a look at the sentence analyzer code and I was wondering what happened to the igo-unidic repo.

**Comment by luckasRanarison** [comment]
Oh sorry, I was wrong and I think I understand now. な, だ,です,... are a form of copula and are treated as verbs. Calling な particle in this case is also not completely correct.

**Comment by JojiiOfficial** [comment]
I agree. The tokenizer outputs it as '助動詞' which can be translated as 'auxiliary verb', this is why its shown as 'verb'. If you have a more fitting translation, feel free to suggest another one.

**Comment by luckasRanarison** [comment]
I think the current one is okay, and I've just realized that jisho.org also do the same thing.

Closing this issue.
