### ISSUE TITLE
Add a way to get back to the main page

### ISSUE THREAD

**Issue by StoneLabs** [WeDontPanic/Jotoba#5]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to get back to the home page (meaning .de/ ) by using the mouse. (AFAIK)

**Describe the solution you'd like**
Perhaps add the logo to the top left on the search result page. Clicking the logo can get you back to the main page as is common in most websites.

**Describe alternatives you've considered**
/

**Additional context**
Perhaps like this:
![image](https://user-images.githubusercontent.com/19885942/141829009-06a9626f-83e0-4268-b40b-16a6adb97883.png)

**Thanks**
You did a great job with this website ngl. I already prefer this over jisho and others. Thanks!

**Comment by Yukaru-san** [comment]
Thanks for the feedback.
For now you can get back to the main page by "searching" with an emptied search bar.

**Comment by JojiiOfficial** [comment]
Tbh I'm not a fan of having an icon in the top left corner. A lot of sites do it and usually it looks good but in this case it looks odd to me. I would agree on a home icon next to the settings icon though. Yet one can still reach the homepage by searching for an empty string, as @Yukaru-san already mentioned.

**Comment by Yukaru-san** [comment]
I am honestly not a fan of having our logo at the top of the page. It looks cleaner without it imo (especially on mobile).
We can go with the home icon instead i guess. Any thoughts on this?

**Comment by Yukaru-san** [comment]
Implemented using a home Icon. Will be released in the next patch!
