### ISSUE TITLE
Replaying kanji stroke animations

### ISSUE THREAD

**Issue by MoshiKoi** [WeDontPanic/Jotoba#6]
Could there be a way to replay the kanji stroke animations without needing to reload the page?

**Comment by Yukaru-san** [comment]
There already is. A klick on the drawn kanji should restart the animation.

**Comment by MoshiKoi** [comment]
Oh, I didn't realize. It doesn't seem very obvious to me though, so maybe you should point that out somewhere on-page.

**Comment by Yukaru-san** [comment]
We'll add that to the discussions, thanks for the feedback.
