### ISSUE TITLE
Safari does not support .ogg playback

### ISSUE THREAD

**Issue by Dorako** [WeDontPanic/Jotoba#7]
It'd be nice to be able to play back the audio in my normal browser. Currently the site just silently fails when hitting one of the audio buttons.

Improvements: 
Easy but bad: Check for platform and only show playback button on compatible browsers.
Hard but good: Implement javascript decoding of .ogg files as a fallback, or store transcoded .mp3/.acc files and offer those for browsers incompatible with .ogg

**Comment by Yukaru-san** [comment]
Thanks for pointing that out. Browser compatibility really is an... interesting topic.
I've added it to our Roadmap.

**Comment by Dorako** [comment]
Cool! This is one of those things where Safari should just really get in line, but the mp3 fallback solution is probably the best - as long as you are ok writing a script transcoding the ogg files and actually storing the mp3 files (they will probably take approximately the same storage that the ogg files are taking, so you can estimate how much that'd be).
On the client side only one file is loaded on playback, so it should be no problem on that end.

**Comment by JojiiOfficial** [comment]
Has been fixed. Coming to Jotoba.de with next patch
