### ISSUE TITLE
Copying multiple kanjis from the result page inserts line breaks between them

### ISSUE THREAD

**Issue by StoneLabs** [WeDontPanic/Jotoba#8]
**Describe the bug**
Copying two or more kanji from the result page inserts line breaks in between the characters.

**To Reproduce**
1. Go to the result of any search
2. Select results as shown in the screenshot below
3. Ctrl+C and Ctrl+V to another program with multiline text input

**Expected behavior**
Copying two or more kanji from the result page should place them into the clipboard without space or newlines in between.

**Screenshots**
![image](https://user-images.githubusercontent.com/19885942/142198991-19f3c564-c1fa-441f-b56d-f551b1a87025.png)
**Explanation**: Copied from left with Ctrl+C, inserted on right with Ctrl+V

**Desktop (please complete the following information):**
 - OS: Windows_NT 10.0 19043
 - Browser Firefox 94.0.1 Build 20211103134640
 - Version ?

Also verified with Chromium 82.0.4050.0 (Developer Build) (64-bit)

**Comment by Yukaru-san** [comment]
Thanks for the detailed description. I'll look into it.
For the time being, you can double click results to copy them without line breaks.

**Comment by marksg7** [comment]
Related bug -- trying to select the Kanji text with Yomichan doesn't work, it can only select one Kanji at once. I believe this is because of the HTML structure -- 

- furigana-kanji-container
  - furigana = こと
  - first kanji = 言
- furigana-kanji-container
  - furigana = ば
  - second kanji = 葉

Jisho handles it in this way:

- furigana container
  - furigana for first kanji = こと
  - furigana for second kanji = ば
- kanji = 言葉

This way is better since the Kanji are continuous in HTML.

**Comment by marksg7** [comment]
@Yukaru-san I can take this one on if it's not a priority for you, let me know if that's ok

**Comment by Yukaru-san** [comment]
One of the reasons I decided to go with the current format is because there were some cases in which Jisho was kinda ugly (see the comparison below).
If you have an idea on how to improve this, you can give it a try!

![image](https://user-images.githubusercontent.com/57414313/142451786-c2f3cdb0-17af-44b7-8c2f-b6f9022a2492.png)
_[My son is busy studying for the examinations tomorrow.]_

**Comment by marksg7** [comment]
Yeah, I'll give it a shot!

**Comment by marksg7** [comment]
Solved the Yomichan issue, but enabling ctrl-c copy while maintaining correct spacing for kanji is going to be very difficult or impossible. @StoneLabs @Yukaru-san thoughts on click-to-copy? Like clicking on the kanji will copy to clipboard?

**Comment by MoshiKoi** [comment]
Here's a quick fiddle I made that I think solves the issue: https://jsfiddle.net/Lkdqsjrx/

Basically, it just abuses `display: table` to align the items properly. As a plus, if you want to enable copying the ruby text, you can do it without it interfering with copying the kanji.

**Comment by marksg7** [comment]
> Here's a quick fiddle I made that I think solves the issue: https://jsfiddle.net/Lkdqsjrx/
> 
> Basically, it just abuses `display: table` to align the items properly. As a plus, if you want to enable copying the ruby text, you can do it without it interfering with copying the kanji.

Hmmm, I still get a tab between the kanji when I paste that into notepad. But I really like your use of display: table -- I was trying to fiddle more with flex boxes but couldn't resolve the copy-paste. I think there's definitely a way to work this.

**Comment by MoshiKoi** [comment]
What about this one? https://jsfiddle.net/jfw89cdh/

This one uses flexboxes and uses `display: content` (from [this stackoverflow answer](https://stackoverflow.com/a/50334135)) to get rid of the weirdness.

**Comment by Yukaru-san** [comment]
Your \<ruby\> approach seems to be working quite nicely. In sentences it will still produce line breaks though.
https://jsfiddle.net/xyw6t9vb/

**Comment by Yukaru-san** [comment]
> Solved the Yomichan issue, but enabling ctrl-c copy while maintaining correct spacing for kanji is going to be very difficult or impossible. @StoneLabs @Yukaru-san thoughts on click-to-copy? Like clicking on the kanji will copy to clipboard?

I'd be fine with click-to-copy if need be. It is currently implemented like that anyway (using a double click)

**Comment by MoshiKoi** [comment]
> Your \<ruby\> approach seems to be working quite nicely. It will still put spaces between segments though.
> https://jsfiddle.net/wkjp3yc8/

You need to make sure that there are no spaces between the elements.

**Comment by Yukaru-san** [comment]
Oh yeah, you are right. I guess we can go with this approach then!

**Comment by marksg7** [comment]
Only thing is that the <ruby> approach doesn't help with the Yomichan issue. sigh...

**Comment by Yukaru-san** [comment]
Solved with [#8](https://github.com/WeDontPanic/Jotoba/pull/14)
